"""Repository protocols. Concrete implementations live in `infrastructure`."""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable

from dijla.domain.entities import (
    Certificate,
    Counterexample,
    Cycle,
    Event,
    Hypothesis,
    Proof,
    Tactic,
    Theorem,
)
from dijla.domain.value_objects import EntityId, TheoremStatus


@runtime_checkable
class HypothesisRepository(Protocol):
    async def add(self, hypothesis: Hypothesis) -> None: ...
    async def get(self, hypothesis_id: EntityId) -> Hypothesis: ...
    async def list(self) -> list[Hypothesis]: ...


@runtime_checkable
class TheoremRepository(Protocol):
    async def add(self, theorem: Theorem) -> None: ...
    async def update(self, theorem: Theorem) -> None: ...
    async def get(self, theorem_id: EntityId) -> Theorem: ...
    async def list(self, *, status: TheoremStatus | None = None) -> list[Theorem]: ...


@runtime_checkable
class ProofRepository(Protocol):
    async def add(self, proof: Proof) -> None: ...
    async def get(self, proof_id: EntityId) -> Proof: ...


@runtime_checkable
class CertificateRepository(Protocol):
    async def add(self, certificate: Certificate) -> None: ...
    async def list(self) -> list[Certificate]: ...


@runtime_checkable
class CounterexampleRepository(Protocol):
    async def add(self, counterexample: Counterexample) -> None: ...
    async def list(self) -> list[Counterexample]: ...


@runtime_checkable
class CycleRepository(Protocol):
    async def add(self, cycle: Cycle) -> None: ...
    async def update(self, cycle: Cycle) -> None: ...
    async def get(self, cycle_id: EntityId) -> Cycle: ...
    async def list(self) -> list[Cycle]: ...


@runtime_checkable
class EventRepository(Protocol):
    async def append(self, event: Event) -> None: ...
    async def stream(self, cycle_id: EntityId) -> AsyncIterator[Event]: ...
    async def list_for_cycle(self, cycle_id: EntityId) -> list[Event]: ...


@runtime_checkable
class TacticRepository(Protocol):
    async def add(self, tactic: Tactic) -> None: ...
    async def list(self) -> list[Tactic]: ...
